"""
Registro central de plantillas del proyecto de Anexo Transaccional.
"""

from plantillas.plantillas_fct import (
    PLANTILLA_BANCO_PRODUCTIVO_NACIONAL,
    PLANTILLA_BANCO_CORDILLERA,
    PLANTILLA_BANCO_SOLIDARIDAD_ANDINA,
    PLANTILLA_TARJETA_CUMBRE_ZENITH,
    PLANTILLA_TARJETA_CUMBRE_PRISMA,
    PLANTILLA_TARJETA_CUMBRE_NORTIS,
    PLANTILLA_TARJETA_CUMBRE_ELITE_PAY,
)



PLANTILLAS_REGISTRADAS = [
    PLANTILLA_BANCO_PRODUCTIVO_NACIONAL,
    PLANTILLA_BANCO_CORDILLERA,
    PLANTILLA_BANCO_SOLIDARIDAD_ANDINA,
    PLANTILLA_TARJETA_CUMBRE_ZENITH,
    PLANTILLA_TARJETA_CUMBRE_PRISMA,
    PLANTILLA_TARJETA_CUMBRE_NORTIS,
    PLANTILLA_TARJETA_CUMBRE_ELITE_PAY,
]
